# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_FileDrive:

    docker:
      - image: cimg/python

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      
      - run:
          name: Run automated tests
          command: python -m pytest
        
      - persist_to_workspace:
          root: ~/project
          paths: 
            - .

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test_FileDrive:
    jobs:
      - build_FileDrive